### ISSUE TITLE
Game crashes on startup due to missing gfx resources

### ISSUE THREAD

**Issue by arjenvanderende** [Fundynamic/dune2themaker4j#174]
I've just made a clean clone of the Git repository and followed the steps in the README to get started. The build succeeds, but starting the game crashes:

```shell
...snip...
Reading ui/icons/icon_deathhand.bmp
AL lib: (WW) FreeContext: (0x7fe7cac65d10) Deleting 64 Source(s)
AL lib: (WW) FreeDevice: (0x7fe7cc21a200) Deleting 1 Buffer(s)
java.lang.RuntimeException: Resource not found: ui/icons/icon_deathhand.bmp
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:185)
	at org.newdawn.slick.Image.<init>(Image.java:192)
	at org.newdawn.slick.Image.<init>(Image.java:166)
	at org.newdawn.slick.Image.<init>(Image.java:154)
	at org.newdawn.slick.Image.<init>(Image.java:132)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesData.createSlickImage(EntitiesData.java:350)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesData.loadImage(EntitiesData.java:328)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesData.addSuperPower(EntitiesData.java:126)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesDataReader.readSuperPowers(EntitiesDataReader.java:95)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesDataReader.fromResource(EntitiesDataReader.java:60)
	at com.fundynamic.d2tm.game.entities.entitiesdata.EntitiesDataReader.fromRulesIni(EntitiesDataReader.java:48)
	at com.fundynamic.d2tm.game.state.PlayingState.createEntityRepository(PlayingState.java:183)
	at com.fundynamic.d2tm.game.state.PlayingState.init(PlayingState.java:90)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
	at org.newdawn.slick.util.Bootstrap.runAsApplication(Bootstrap.java:24)
	at com.fundynamic.d2tm.Game.main(Game.java:83)
```

Seems like `ui/icons/icon_deathhand.bmp` hasn't been checked into the repo.

**Comment by stefanhendriks** [comment]
thx for checking @arjenvanderende , just pushed a branch that should fix this. Plz confirm :)
